<template>
<div>
    Dialog的文档
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
    <p>dialog文档</p>
</div>
</template>
